"use client";
import * as faceapi from "face-api.js";
import { useCallback, useEffect, useRef, useState } from "react";
type Mode = "login" | "enroll";
export default function HomePage() {
 const videoRef=useRef<HTMLVideoElement>(null); const streamRef=useRef<MediaStream|null>(null);
 const [mode,setMode]=useState<Mode>("login"); const [camera,setCamera]=useState<"user"|"environment">("user"); const [setupToken,setSetupToken]=useState("");
 const [modelsReady,setModelsReady]=useState(false); const [cameraReady,setCameraReady]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("Memuat model pengenalan wajah..."); const [messageType,setMessageType]=useState<"normal"|"error"|"success">("normal");
 useEffect(()=>{let alive=true;Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri("/models"),faceapi.nets.faceLandmark68Net.loadFromUri("/models"),faceapi.nets.faceRecognitionNet.loadFromUri("/models")]).then(()=>{if(alive){setModelsReady(true);setMessage("Model siap. Aktifkan kamera untuk memulai.");}}).catch(()=>{if(alive){setMessage("Model belum tersedia. Jalankan npm run download:models lalu deploy ulang.");setMessageType("error");}});return()=>{alive=false;streamRef.current?.getTracks().forEach(t=>t.stop());};},[]);
 const stopCamera=useCallback(()=>{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setCameraReady(false);},[]);
 const startCamera=useCallback(async()=>{stopCamera();try{if(!navigator.mediaDevices?.getUserMedia)throw new Error("Browser tidak mendukung kamera. Gunakan HTTPS.");const stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:camera},width:{ideal:640},height:{ideal:480}}});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play();}setCameraReady(true);setMessage("Kamera aktif. Pastikan wajah terlihat jelas.");setMessageType("normal");}catch(error){setMessage(error instanceof Error?error.message:"Tidak dapat mengakses kamera.");setMessageType("error");}},[camera,stopCamera]);
 async function captureDescriptor(){if(!videoRef.current||!modelsReady||!cameraReady)throw new Error("Model dan kamera harus siap.");const result=await faceapi.detectSingleFace(videoRef.current,new faceapi.TinyFaceDetectorOptions({inputSize:320,scoreThreshold:0.5})).withFaceLandmarks().withFaceDescriptor();if(!result)throw new Error("Wajah tidak terdeteksi. Hadapkan wajah ke kamera dan coba lagi.");return Array.from(result.descriptor);}
 async function submit(){setBusy(true);setMessage("Memeriksa wajah...");setMessageType("normal");try{const descriptor=await captureDescriptor();const response=await fetch(mode==="enroll"?"/api/auth/enroll":"/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(mode==="enroll"?{descriptor,setupToken}:{descriptor})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"Autentikasi gagal.");if(mode==="login"){window.location.assign("/dashboard");return;}setSetupToken("");setMode("login");setMessage("Pendaftaran wajah berhasil. Sekarang login dengan wajah terdaftar.");setMessageType("success");}catch(error){setMessage(error instanceof Error?error.message:"Terjadi kesalahan.");setMessageType("error");}finally{setBusy(false);}}
 function changeMode(next:Mode){setMode(next);setMessage(next==="enroll"?"Pendaftaran pertama memerlukan token setup rahasia.":"Arahkan wajah admin ke kamera.");setMessageType("normal");}
 return <main className="shell"><section className="panel"><div className="brand"><div className="brand-mark">W</div><div><div className="brand-title">Admin Secure Access</div><div className="small">Autentikasi wajah</div></div></div><div className="eyebrow">PANEL ADMIN</div><h1>Masuk dengan wajah</h1><p className="muted">Gunakan kamera perangkat untuk memverifikasi wajah admin yang sudah terdaftar.</p>
 <div className="tabs"><button className={mode==="login"?"active":""} onClick={()=>changeMode("login")}>Login</button><button className={mode==="enroll"?"active":""} onClick={()=>changeMode("enroll")}>Daftarkan wajah</button></div>
 {mode==="enroll"&&<div className="field"><label htmlFor="setup-token">Token pendaftaran admin</label><input id="setup-token" className="text-input" type="password" autoComplete="off" value={setupToken} onChange={e=>setSetupToken(e.target.value)} placeholder="Masukkan ADMIN_SETUP_TOKEN"/></div>}
 <div className="field"><label htmlFor="camera-select">Pilih kamera</label><select id="camera-select" className="select" value={camera} onChange={e=>{setCamera(e.target.value as "user"|"environment");stopCamera();}}><option value="user">Kamera depan</option><option value="environment">Kamera belakang</option></select></div>
 <div className="camera"><video ref={videoRef} muted playsInline aria-label="Pratinjau kamera untuk verifikasi wajah"/><span className="camera-label">{cameraReady?"KAMERA AKTIF":"KAMERA NONAKTIF"}</span></div>
 <div className="controls"><button className="button secondary" onClick={startCamera} disabled={!modelsReady||busy}>Aktifkan kamera</button><button className="button secondary" onClick={stopCamera} disabled={!cameraReady||busy}>Matikan kamera</button></div>
 <button className="button full" onClick={submit} disabled={!modelsReady||!cameraReady||busy||(mode==="enroll"&&!setupToken.trim())}>{busy?"Memproses...":mode==="enroll"?"Daftarkan wajah admin":"Login dengan wajah"}</button>
 <div className={`notice ${messageType==="error"?"error":messageType==="success"?"success":""}`} role="status">{message}</div><p className="small">Kamera membutuhkan izin browser dan HTTPS di production. Pengenalan descriptor ini belum memiliki pemeriksaan liveness, sehingga jangan jadikan satu-satunya pengaman untuk sistem berisiko tinggi.</p><div className="footer">Sesi admin berakhir setelah 20 menit tanpa aktivitas.</div>
 </section></main>;
}
